package com.legacy.linker.generator;

import com.legacy.linker.model.VbProject;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class MarkdownGenerator {

    private final Path outputDir;

    public MarkdownGenerator(Path outputDir) {
        this.outputDir = outputDir;
    }

    public void generate(List<VbProject> projects) throws IOException {
        Path docsDir = outputDir.resolve("docs");
        Files.createDirectories(docsDir);

        // 1. Generate mkdocs.yml
        generateMkDocsConfig(projects);

        // 2. Generate Home Page
        generateIndex(docsDir, projects);

        // 3. Generate Project Pages
        for (VbProject project : projects) {
            generateProjectPage(docsDir, project, projects);
        }
    }

    private void generateMkDocsConfig(List<VbProject> projects) throws IOException {
        StringBuilder yaml = new StringBuilder();
        yaml.append("site_name: Legacy VB Wiki\n");
        yaml.append("theme:\n");
        yaml.append("  name: material\n");
        yaml.append("  features:\n");
        yaml.append("    - navigation.expand\n");
        yaml.append("    - search.highlight\n");
        yaml.append("    - content.code.copy\n");
        yaml.append("markdown_extensions:\n");
        yaml.append("  - pymdownx.superfences:\n");
        yaml.append("      custom_fences:\n");
        yaml.append("        - name: mermaid\n");
        yaml.append("          class: mermaid\n");
        yaml.append("          format: !!python/name:pymdownx.superfences.fence_code_format\n");
        yaml.append("nav:\n");
        yaml.append("  - Home: index.md\n");

        // Sorting projects by name for better navigation
        projects.stream()
                .sorted((p1, p2) -> p1.name().compareToIgnoreCase(p2.name()))
                .forEach(p -> {
                    String filename = getSafeFilename(p.name());
                    yaml.append("  - ").append(p.name()).append(": ").append(filename).append("\n");
                });

        Files.writeString(outputDir.resolve("mkdocs.yml"), yaml.toString());
    }

    private void generateIndex(Path docsDir, List<VbProject> projects) throws IOException {
        StringBuilder md = new StringBuilder();
        md.append("# Legacy System Overview\n\n");
        md.append("Welcome to the mapped documentation of the Legacy VB system.\n\n");
        md.append("## Project Statistics\n\n");
        md.append("| Project Name | Exe Name | Forms | Modules | Outbound Calls |\n");
        md.append("| :--- | :--- | :---: | :---: | :---: |\n");

        for (VbProject p : projects) {
            md.append(String.format("| [%s](%s) | `%s` | %d | %d | %d |\n",
                    p.name(), getSafeFilename(p.name()), p.exeName(),
                    p.forms().size(), p.modules().size(),
                    p.dependencies() != null ? p.dependencies().size() : 0));
        }

        md.append("\n\nGenerated by LegacyLinker.");

        Files.writeString(docsDir.resolve("index.md"), md.toString());
    }

    private void generateProjectPage(Path docsDir, VbProject p, List<VbProject> projects) throws IOException {
        StringBuilder md = new StringBuilder();
        md.append("# ").append(p.name()).append("\n\n");

        md.append("## Basic Information\n");
        md.append("- **Exe Name**: `").append(p.exeName()).append("`\n");
        md.append("- **Project Path**: `").append(p.path().toString()).append("`\n\n");

        md.append("## Components\n");

        md.append("### Forms (").append(p.forms().size()).append(")\n");
        if (p.forms().isEmpty()) {
            md.append("_No forms found._\n");
        } else {
            for (Path f : p.forms()) {
                md.append("- `").append(f.getFileName().toString()).append("`\n");
            }
        }
        md.append("\n");

        md.append("### Modules (").append(p.modules().size()).append(")\n");
        if (p.modules().isEmpty()) {
            md.append("_No modules found._\n");
        } else {
            for (Path m : p.modules()) {
                md.append("- `").append(m.getFileName().toString()).append("`\n");
            }
        }

        md.append("## Connections\n");
        if (p.dependencies().isEmpty()) {
            md.append("_No outgoing shell calls detected._\n");
        } else {
            md.append("### Outbound Calls\n");
            md.append("This project calls the following external executables:\n\n");
            md.append("| Target | Source File | Line | Content |\n");
            md.append("| :--- | :--- | :---: | :--- |\n");

            for (com.legacy.linker.model.ProjectDependency dep : p.dependencies()) {
                // Try to resolve the target exe to a project name
                String targetLink = resolveLink(dep.targetExeName(), projects);
                md.append(String.format("| %s | `%s` | %d | `%s` |\n",
                        targetLink,
                        dep.sourceFile().getFileName().toString(),
                        dep.lineNumber(),
                        dep.rawLineContent().replace("|", "\\|").trim() // Escape pipe table char
                ));
            }

            md.append("\n### Dependency Graph\n");
            md.append("```mermaid\n");
            md.append("graph LR\n");
            md.append("  Current[").append(p.name()).append("]\n");
            for (com.legacy.linker.model.ProjectDependency dep : p.dependencies()) {
                String targetName = resolveName(dep.targetExeName(), projects);
                String safeTarget = targetName.replaceAll("[^a-zA-Z0-9]", "");
                md.append("  Current --> |Calls| ").append(safeTarget).append("[").append(targetName).append("]\n");
            }
            md.append("```\n");
        }

        Files.writeString(docsDir.resolve(getSafeFilename(p.name())), md.toString());
    }

    // Naive lookup: find the first project that produces this exe
    private String resolveLink(String exeName, List<VbProject> projects) {
        return projects.stream()
                .filter(p -> p.exeName().equalsIgnoreCase(exeName))
                .findFirst()
                .map(p -> String.format("[%s](%s)", p.name(), getSafeFilename(p.name())))
                .orElse(String.format("`%s` (Unknown)", exeName));
    }

    private String resolveName(String exeName, List<VbProject> projects) {
        return projects.stream()
                .filter(p -> p.exeName().equalsIgnoreCase(exeName))
                .findFirst()
                .map(VbProject::name)
                .orElse(exeName);
    }

    private String getSafeFilename(String name) {
        return name.replaceAll("[^a-zA-Z0-9_\\-]", "_") + ".md";
    }
}
